CREATE DATABASE UPESUNIVERSITY

USE UPESUNIVERSITY

--1

CREATE TABLE STUDENT
(Name VARCHAR(30  NOT NULL,
StudentNumber INTEGER NOT NULL,
Class CHAR NOT NULL,
Major CHAR(4),
PRIMARY KEY (StudentNumber));

CREATE TABLE COURSE
(CourseName VARCHAR(30) NOT NULL,
CourseNumber CHAR(8) NOT NULL,
CreditHours INTEGER,
Department CHAR(4),
PRIMARY KEY (CourseNumber),
UNIQUE (CourseName));

CREATE TABLE PREREQUISITE
(CourseNumber CHAR(8) NOT NULL,
PrerequisiteNumber CHAR(8) NOT NULL,
PRIMARY KEY (CourseNumber, PrerequisiteNumber),
FOREIGN KEY (CourseNumber) REFERENCES COURSE (CourseNumber),
FOREIGN KEY (PrerequisiteNumber) REFERENCES COURSE (CourseNumber));

CREATE TABLE SECTION
(SectionIdentifier INTEGER NOT NULL,
CourseNumber CHAR(8) NOT NULL,
Semester VARCHAR(6) NOT NULL,
Year CHAR(4) NOT NULL,
Instructor VARCHAR(15),
PRIMARY KEY (SectionIdentifier),
FOREIGN KEY (CourseNumber) REFERENCES COURSE (CourseNumber));

CREATE TABLE GRADE_REPORT
(StudentNumber INTEGER NOT NULL,
SectionIdentifier INTEGER NOT NULL, 
Grade CHAR,
PRIMARY KEY (StudentNumber, SectionIdentifier),
FOREIGN KEY (StudentNumber) REFERENCES STUDENT (StudentNumber),
FOREIGN KEY (SectionIdentifier) REFERENCES SECTION (SectionIdentifier)); 

--2

--STUDENT
INSERT INTO STUDENT VALUES ('SMITH',17,'1','CS');
INSERT INTO STUDENT VALUES ('BROWN',8,'2','CS');

--COURSE
INSERT INTO COURSE VALUES ('Intro to Computer Science','CS1310','4','CS');
INSERT INTO COURSE VALUES ('Data Structures','CS3320',4,'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics','MATH2410','3','MATH');
INSERT INTO COURSE VALUES ('Database','CS3380','3','CS');

--SECTION
INSERT INTO SECTION VALUES (85,'MATH2410','FALL','07','King');
INSERT INTO SECTION VALUES (92,'CS1310','FALL','07','Anderson');
INSERT INTO SECTION VALUES (102,'CS3320','SPRING','08','Kruth');
INSERT INTO SECTION VALUES (112,'MATH2410','FALL','08','Chang');
INSERT INTO SECTION VALUES (119,'CS1310','FALL','08','Anderson');
INSERT INTO SECTION VALUES (135,'CS3380','FALL','08','Stone');

--GRADE_REPORT
INSERT INTO GRADE_REPORT VALUES (17,112,'B');
INSERT INTO GRADE_REPORT VALUES (17,119,'C');
INSERT INTO GRADE_REPORT VALUES (8,85,'A');
INSERT INTO GRADE_REPORT VALUES (8,92,'A');
INSERT INTO GRADE_REPORT VALUES (8,102,'B');
INSERT INTO GRADE_REPORT VALUES (8,135,'A');

--PREREQUISITES
INSERT INTO PREREQUISITE VALUES ('CS3380','CS3320');
INSERT INTO PREREQUISITE VALUES ('CS3380','MATH2410');
INSERT INTO PREREQUISITE VALUES ('CS3320','CS1310');

--3

SELECT Name
FROM STUDENT
WHERE Major='CS'

SELECT CourseName
FROM COURSE, SECTION
WHERE COURSE.CourseNumber=SECTION.CourseNumber AND Instructor='King'
AND (Year='07' OR Year='08')

SELECT CourseNumber, Semester, Year, COUNT(*)
FROM SECTION, GRADE_REPORT
WHERE Instructor='King' AND SECTION.SectionIdentifier=GRADE_REPORT.SectionIdentifier
GROUP BY CourseNumber, Semester, Year

SELECT Name, CourseName, C.CourseNumber, CreditHours, Semester, Year, Grade
FROM STUDENT ST, COURSE C, SECTION S, GRADE_REPORT G
WHERE Class=4 AND Major='CS' AND ST.StudentNumber=G.StudentNumber AND G.SectionIdentifier=S.SectionIdentifier AND S.CourseNumber=C.CourseNumber

INSERT INTO STUDENT
VALUES ('Johnson', 25, 1, 'MATH')

UPDATE STUDENT
SET CLASS = 2
WHERE Name='Smith'

INSERT INTO COURSE
VALUES ('Knowledge Engineering','CS4390', 3,'CS')

DELETE FROM STUDENT
WHERE Name='Smith' AND StudentNumber=17