CREATE TABLE EMPLOYEE
( 
EMPNO INTEGER NOT NULL, 
ENAME VARCHAR(30) NOT NULL,
JOB VARCHAR(20) NOT NULL,
MGR INTEGER,
HIREDATE  DATE, 
SAL INTEGER,
COMM INTEGER,
DEPTNO INTEGER
PRIMARY KEY (EMPNO), -- Primary key constraint
FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);
GO
exec sp_columns EMPLOYEE
GO
CREATE TABLE DEPARTMENT
( 
DEPTNO INTEGER NOT NULL,
DNAME VARCHAR(15) NOT NULL,
LOC VARCHAR(30),
PRIMARY KEY (DEPTNO)
)